### ISSUE TITLE
Fault example from pack Arm:CMSIS-View@1.2.0 not shown in Create New Solution with Rev.C board

### ISSUE THREAD

**Issue by ReinhardKeil** [ARM-software/vscode-cmsis-csolution#100]
Version: VS Code CMSIS Solution 1.40

I would expect to see the "Fault" example.  It is not shown.

![image](https://github.com/user-attachments/assets/b72e5758-d033-4786-86b5-3ad76d2c94d9)

**Comment by jkrech** [comment]
After adding the `revision=` attribute to the example in the pack description file, the example shows for me.
Is the general expectation for an example that specifies a board without the `revision` would show for boards with any `revision` or no `revision` specified at all.

Currently the only work around I see is editing the installed pdsc file.

**Comment by ReinhardKeil** [comment]
When no `revision` is specified in the example it should show up for any board revision.

**Comment by JonatanAntoni** [comment]
This is expected to work in latest main:
<img width="1512" alt="Bildschirmfoto 2024-11-12 um 08 17 36" src="https://github.com/user-attachments/assets/aba280eb-83d5-4a79-b0cf-b8ba5772754d">

It may take a while to load the examples. The dropdown shall be updated after a view seconds to list "LOCAL CMSIS SOLUTION EXAMPLES".
