### ISSUE TITLE
Improvements on CMSIS Outline View: default collapse, number of components, add group to project, context menu, delete

### ISSUE THREAD

**Issue by ReinhardKeil** [ARM-software/vscode-cmsis-csolution#107]
These are suggestions to improve the Project Outline in the CMSIS-View

- By default, Components, linker, constructed files should be collapsed to put the focus on user code
  ![image](https://github.com/user-attachments/assets/e4f33f7d-de36-4272-b853-0fa75c8f0ca6)

- Add on "Components" the number, i.e. "Components (10)" similar to the Manage Software Components view.

- Add at project level an Action Button to Add Groups

- Q: Is it possible to add a context menu similar to Explorer View?   A: Yes

Deferring to a new issue:
- Enable 'Delete' button to remove groups and files.  There should be an dialog similar to the Explore View with the options 
   - "Remove from project only"
   - "Move to Recycle Bin"
   - "Cancel"

**Comment by mguzmanm** [comment]
- [Done] By default, Components, linker, constructed files should be collapsed to put the focus on user code
- [Done] Add on "Components" the number, i.e. "Components (10)" similar to the Manage Software Components view.
- [Done] Add at project level an Action Button to Add Groups

**Comment by jkrech** [comment]
Confirmed based on internal build from main branch 2024-12-05
