### ISSUE TITLE
Template Project with explicit Target "MyTarget" results incorrect project

### ISSUE THREAD

**Issue by ReinhardKeil** [ARM-software/vscode-cmsis-csolution#109]
When using Create New Project with explicit Target name as shown below
- Ambiq Micro::Apollo3 Blue EVB:Ver 1.0
- target-type: MyTarget
- Template: Blank 

![image](https://github.com/user-attachments/assets/25340208-7d8c-4128-96a8-1c7d151d1e69)

An incorrect project is created with:
- missing project
- that shows only "Loading" in the CMSIS View

![image](https://github.com/user-attachments/assets/f8e5532b-1884-4f08-81f4-bae099c7311c)

**Expected behavior**
- Project is correctly generated
- CMSIS View tolerates such incorrect projects and shows an error.

**Comment by ReinhardKeil** [comment]
Test project: [Blank_solution.zip](https://github.com/user-attachments/files/17620787/Blank_solution.zip)

**Comment by jkrech** [comment]
@ReinhardKeil this is working correctly in the released version 1.40 but fails for the latest unpublished builds.
As far as I can see this is not related to the renamed target-type. The "Create Solution" dialog is missing the part that by default adds the `Project.cproject.yml ` project but also allows to add additional projects.

**Comment by ReinhardKeil** [comment]
no, cannot duplicate it with the official release.
