### ISSUE TITLE
Deselected projects in "Manage Solution Settings" remain active 

### ISSUE THREAD

**Issue by chentang16** [ARM-software/vscode-cmsis-csolution#110]
Type: Bug Report

**Describe the bug**
- OS and Version: Windows 11
- VS Code Version: 1.95.1
- Extension Version: 1.40.0
- Target Device: STM32F7-Disco

When creating a MWv8 example project by using the reference projects template in VS Code as following https://arm-software.github.io/MDK-Middleware/latest/General/working_with_examples.html#autotoc_md1 , all reference projects are active by default. After disabling most projects in "Manage Solution Settings" as shown in the attached video screenshot, and build the project, Deselected projects in "Manage Solution Settings" reverts to be active again and is included in the build process.

**To Reproduce**
As shown in the attached video screenshot.

**Expected behavior**
Only the selected active project in "Manage Solution Settings" should remain active and being built.

https://github.com/user-attachments/assets/ada93256-c860-4d00-86e8-1cea66ce5c85

**Comment by ReinhardKeil** [comment]
This is already fixed in the next upcoming version
