### ISSUE TITLE
Converting uVision projects via New Project Workflow adds board

### ISSUE THREAD

**Issue by ReinhardKeil** [ARM-software/vscode-cmsis-csolution#114]
When using the  New Project Workflow to convert a uVision project, the board information gets added. 

This is not in the original uVision project and also not added by the uv2csolution utility. 
Therefore VS Code should not add a board information in this case, leaving the uv2csolution converted project unchanged.

**Comment by thorstendb-ARM** [comment]
Seems to affect LOCAL projects for UV2CSOLUTION. "Local Examples" were an extra data path in v1.44 and accidently added board information. Should be fixed in the next version.

**Comment by ReinhardKeil** [comment]
seems to work
