### ISSUE TITLE
Do not show UV projects that require AC5 in Create new solution dialog

### ISSUE THREAD

**Issue by ReinhardKeil** [ARM-software/vscode-cmsis-csolution#116]
**Note:** To duplicate this issue, first select a board that has csolution examples, i.e EVK-MIMXRT1060 and view the projects.

uVision examples that are created for AC5 cannot be converted. On the web side these examples are marked with AC5.

In the Create new solution dialog such examples should not be shown.

This is a board that has such examples https://www.keil.arm.com/boards/abov-starterkit-a31g112cl-v11-9cec7c0/projects/

**Comment by JonatanAntoni** [comment]
Examples retrieved from Core Tools can't be filtered unfortunately. The web search results retrieved via Solar search contain a `convertible` flag indicating its compatibility (via uv2csolution). We plan to list only those uVision examples returned from Solar which are convertible.

See Arm-Debug/vscode-cmsis-csolution#1919

**Comment by JonatanAntoni** [comment]
cc @thorstendb-ARM

**Comment by jkrech** [comment]
I confirm that uVision projects from the Web that require AC5 are no longer displayed, whereas uVision projects from installed packs are listed even if they use AC5 as there is no information in the pdsc file indicating whether a project uses AC5 or AC6.
