### ISSUE TITLE
`cmsis-csolution.getBinaryFile` command isn't always returning the correct path

### ISSUE THREAD

**Issue by thegecko** [ARM-software/vscode-cmsis-csolution#12]
As mentioned over at:

https://github.com/ARM-software/vscode-embedded-debug/issues/1#issuecomment-1343012722

The `cmsis-csolution.getBinaryFile` command isn't always returning the correct path.

cc @fredo514

**Comment by mcgordonite** [comment]
It looks like the extension isn't handling "default" build and target types correctly. If you don't specify any build types for example, the binary name won't include a ".buildType" part.

We'll fix this in an upcoming release.

**Comment by mcgordonite** [comment]
This was resolved in version 0.11.0.
