### ISSUE TITLE
Show open document for API 

### ISSUE THREAD

**Issue by ReinhardKeil** [ARM-software/vscode-cmsis-csolution#122]
The API documentation is not accessible when the component has own documentation.

Is it possible to add the API documentation to the API file instead and offer an Action icon (in this picture at the level of "cmsis_os2.h"?

![image](https://github.com/user-attachments/assets/c4e7eb4f-8d16-4c8f-aa32-3848f3710bef)

**Comment by jkrech** [comment]
Initial investigation suggests that should be doable and it has been added to the backlog for the upcoming release.

**Comment by mguzmanm** [comment]
API documentation is now accesible as required.

**Comment by jkrech** [comment]
Component documentation and API documentation are selectable (vsix from 2024-11-28)
![image](https://github.com/user-attachments/assets/0f914cf4-c10d-46ec-9768-01e65ee475a3)

**Comment by Elise-Kaminski** [comment]
Documented with https://github.com/Arm-Debug/ks-vscode-extension-docs/pull/272
