### ISSUE TITLE
Loading Solution - Busy status never stops

### ISSUE THREAD

**Issue by ReinhardKeil** [ARM-software/vscode-cmsis-csolution#139]
CMSIS Solution 1.47 - internal (Windows)

Use this repo: https://github.com/Open-CMSIS-Pack/Sensor-SDK-Example

When opening the Folder, the busy status on Loading solution never stops.
It is not expected that the solution correctly converts as the repo only contains incomplete csolution projects that require layers.

![image](https://github.com/user-attachments/assets/792970df-64ea-4570-911f-ed23d1a438dc)

**Comment by jkrech** [comment]
This seems to be related to the fact that there is no target-type defined and that no initial context-set can be found or validated.
Once loaded, removing the target-type does not impact the view and loading.
This needs further investigation.

**Comment by JonatanAntoni** [comment]
It could look like this instead:
![vscode](https://github.com/user-attachments/assets/d2cb4037-4192-49e2-9c86-4f196f6ae2e9)

**Comment by jkrech** [comment]
Using CMSIS Solution Extension internal build 2024-12-11
a) loading the reproducer above now displays in red "[Solution invalid]" in the status bar
b) when clicking on the status bar the CMSIS Solution output displays:
mpl3115.csolution.yml:14:3 - error csolution: node 'target-types' shall contain sequence elements
c) The "Manage Solution" view does not show any target-type | Board | Device entries and gracefully handles this error scenario.

![image](https://github.com/user-attachments/assets/fd513626-182b-4205-bb44-a6d4597124bb)
