### ISSUE TITLE
ReadMe doc to setup development environment

### ISSUE THREAD

**Issue by ChrisSJard** [ARM-software/vscode-cmsis-csolution#14]
Type: Feature Request

**Update to ReadMe.md**

-> _General Notes Section_:
1. Was difficult to separate header sections when first reading the document as increased font size does not standout enough, adding a bullet list separator or number list separator would allow them to stand out more.
e.g. -> General Section
e.g  * General Section
e.g 1. General Section

2. Remove string quotes  around code snippets.

-> _General Comments Section_
1. Would be good to describe a binary directory is noted as a "bin", as it is not common knowledge useless the reader familiar with embedded systems terminology.

-> _Install the Arm GNU Toolchain Section_
1. Checking installation using the command below, would be useful to know to go to file directory location where arm-none-eabi-g++ is located after the install.
`arm-none-eabi-g++ --help`

-> _Install the CMSIS-Toolbox Section_
Step 6: this overlaps with General comments section , but it was more useful here while general section confused me.
the code `xattr -d com.apple.quarantine <cmsis-toolbox-installation-dir>/bin/` , was not clear that files in the bin file of cmsis-toolbox were the files we had to de-quarantine. Maybe showing example of example path/to/cmsis-toolbox/bin/cbuild .
step 7:
Maybe saying you may need to open cmd terminal in bin file to test in environment variables were not installed correctly.

**Comment by mcgordonite** [comment]
Closing: this will be resolved in the next release of the extension.
