### ISSUE TITLE
Change names

### ISSUE THREAD

**Issue by ReinhardKeil** [ARM-software/vscode-cmsis-csolution#140]
Suggest these changes:

"Solution Folder"  -> "Solution Sub Folder"
"Solution Location" -> "Solution Base Folder

![image](https://github.com/user-attachments/assets/71acbf6e-f302-477e-b66c-9813b5d40685)

**Comment by MiloradCvjetkovic** [comment]
Or maybe we should have:
`Solution Name` for name of the .csolution.yml file, and
`Solution Folder` for directory where .csolution.yml file sits.

**Comment by thorstendb-ARM** [comment]
Done:
![image](https://github.com/user-attachments/assets/09939c95-19cd-4d15-ad40-69bb725ae89f)

**Comment by jkrech** [comment]
Confirmed with internal build from main: 2024-12-05 -> will be in 2.46 release
