### ISSUE TITLE
Review "Initialize CMSIS Solution" command

### ISSUE THREAD

**Issue by ReinhardKeil** [ARM-software/vscode-cmsis-csolution#141]
Command  "Initialize CMSIS Solution" creates:

```
.vscode\launch.json
.vscode\tasks.json
vcpkg-configuration.json
```

This files need review.

**launch.json + tasks.json**

What exactly is passed:
 - how does a Serial Number apply to STLink debug adapters? 
 - what Processor Name is expected (in case of multi-core).

```
            "serialNumber": "${command:device-manager.getSerialNumber}",
            "programs": "${command:cmsis-csolution.getBinaryFiles}",
            "cmsisPack": "${command:cmsis-csolution.getTargetPack}",
            "deviceName": "${command:cmsis-csolution.getDeviceName}",
            "processorName": "${command:cmsis-csolution.getProcessorName}"
```

**vcpkg-configuration.json**

Minimum CMSIS-Toolbox required is 2.6.0.

```
    "requires": {
        "arm:tools/kitware/cmake": "^3.28.4",
        "arm:tools/ninja-build/ninja": "^1.11.1",
        "arm:tools/open-cmsis-pack/cmsis-toolbox": "^2.2.1", 
        "arm:compilers/arm/armclang": "^6.21.0",
        "arm:debuggers/arm/armdbg": "*"
    }
```

**Comment by jkrech** [comment]
Answers:
a) Device Manager retrieves Serial Number from ST-Link 
![Image](https://github.com/user-attachments/assets/ec1a4035-b100-4a81-9727-c54d379e3b9b)
b) If the processor is not clear from the context in which the run/debug button is pressed (or when launching the task out of context), no processor is specified and the user will be given the choice.
If the run/debug button is used on the context level, the processor of that context is returned by the extension.
c) The content of the default vcpkg-configuration file written by the command "Initialize CMSIS Solution" is managed in the "Arm Keil Studio Pack" VS Code extension. With the next patch release 1.18.4 the default version of the CMSIS-Toolbox will be set on 2.7.0.
