### ISSUE TITLE
Link to "getting started guide"

### ISSUE THREAD

**Issue by ReinhardKeil** [ARM-software/vscode-cmsis-csolution#142]
As the CMSIS Solution extension is vendor neutral, we need to rethink the link "getting started guide".

![image](https://github.com/user-attachments/assets/f5b413cd-664e-4334-839a-492a2d5e04ac)

**Comment by KeilChris** [comment]
You're mixing up things here. This is the Keil Studio Pack documentation which can very well have a GSG for it.

**Comment by KeilChris** [comment]
This is a user interface problem.

**Comment by jkrech** [comment]
Is this addressed by #145

**Comment by ReinhardKeil** [comment]
duplicate
