### ISSUE TITLE
.cmake changed structure in new version

### ISSUE THREAD

**Issue by ManInNight** [ARM-software/vscode-cmsis-csolution#19]
Hello,
I am not sure from the instructions if the information given for Windows is correct, because the template .cmake file has changed from what is given in the instructions:

############### EDIT BELOW ###############
set(TOOLCHAIN_ROOT "C:\Program Files (x86)\Arm GNU Toolchain arm-none-eabi\12.2 rel1\bin")
set(TOOLCHAIN_VERSION "12.2.1")
set(PREFIX arm-none-eabi-)
set(EXT .exe)

Are these settings correct for Windows?

**Comment by mcgordonite** [comment]
Hi, thanks for the feedback. That looks correct, if you have installed arm-none-eabi-gcc in that directory.

We will update the README to match the new template in the next release.

**Comment by mcgordonite** [comment]
This was updated in release 0.12.0.
