### ISSUE TITLE
Active solution fail to load the project details

### ISSUE THREAD

**Issue by LMESTM** [ARM-software/vscode-cmsis-csolution#23]
Type: Bug Report

Active solution fail to load the project details. 
A colleague of mine installed the extension 
csolution is listed but not Target Type / Build Type / Project.
The same project works fine on other colleagues environment

![image](https://user-images.githubusercontent.com/17590297/224372093-1d6cf04c-5558-4d3b-b077-795a8a7dcf27.png)

It comes together with an error popup:
![image](https://user-images.githubusercontent.com/17590297/224372688-e2aecb2d-11b8-46d0-827e-bebabe9d0792.png)

There is also an error that we don't understand in the output channel 
![image](https://user-images.githubusercontent.com/17590297/224373034-7eb8ed7c-0df4-4d2b-97a0-4c3a89cd7bcd.png)
maybe that can help explaining the root cause ?
 
**Describe the bug**
- OS and Version: windows
- VS Code Version: tbc
- Extension Version: Keil Studio pack for web v1.3.2
- Target Device: STM32
- Other extensions you installed (and if the issue persists after disabling them):

**To Reproduce**
Not sure how to reproduce this issue ...
If there is anything we can look at, just let us know

**Comment by mcgordonite** [comment]
Are you working behind a proxy? We've had a few reports of problems, but they seem to be resolved by configuring the environment variables here: "2. Configure an HTTP proxy" in https://github.com/ARM-software/vscode-cmsis-csolution#install-the-cmsis-toolbox.

**Comment by LMESTM** [comment]
@mcgordonite - thanks for the hint !
we confirm that the problem is related to PROXY settings and mor particularly from not setting NO_PROXY variable.  Maybe the displayed error might be more explicit for users  ?

**Comment by mcgordonite** [comment]
Great, glad to hear the issue was resolved.

> Maybe the displayed error might be more explicit for users ?

Good suggestion. We'll investigate showing a notification or other message with guidance in situations like this.
