### ISSUE TITLE
Fix install documentation for Windows

### ISSUE THREAD

**Issue by escherstair** [ARM-software/vscode-cmsis-csolution#3]
In Readme.md I see
https://github.com/ARM-software/vscode-cmsis-csolution/blob/main/README.md#modify-extension-settings

1. Go to Code > Preferences > Settings.

but this is true for macOS

For Windows (and Linux, probably) it is
1. Go to **File** > Preferences > Settings.

**Comment by mcgordonite** [comment]
The README updated in version 0.9.0 to include Windows instructions here.
