### ISSUE TITLE
Problems with HelloWorld solution in tutorial

### ISSUE THREAD

**Issue by DavidA2014** [ARM-software/vscode-cmsis-csolution#30]
In the tutorial, for DualCore\HelloWorld.csolution.yml, I see these problems:

```
required pack: ARM::CMSIS not installed
required pack: NXP::K32L3A60_DFP@15.0.0 not installed
```

The .yml contains:

```
  packs:
    - pack: ARM::CMSIS
    - pack: NXP::K32L3A60_DFP@15.0.0
```

but extension 'Arm CMSIS solution' is installed. How can I fix that error?

I am using the ARM MPS2 development board. Which pack should I install?

**Comment by Frisc98** [comment]
Sounds like you need to download pack solutions. Try opening up command pallete and run `CMSIS: Install required packs for active solution`

**Comment by mcgordonite** [comment]
I'm closing this issue, @Frisc98's solution should resolve your problem. Let us know if you're still having problems.
