### ISSUE TITLE
MIMX8ML8 and MIMX8ML6 devices not available in "New CMSIS solution"

### ISSUE THREAD

**Issue by escherstair** [ARM-software/vscode-cmsis-csolution#31]
Type: Feature Request

I know that "New CMSIS solution" is experimental, but I would like asking a feature request.
I can see some of the members of NXP iMX8M family
![immagine](https://user-images.githubusercontent.com/22594460/236430222-b1655ff8-1953-488a-b34e-fc1e88c0ec56.png)

but I cannot see MIMX8ML8 (i.e., [iMX8M-Plus Quad](https://www.nxp.com/products/processors-and-microcontrollers/arm-processors/i-mx-applications-processors/i-mx-8-applications-processors/i-mx-8m-plus-arm-cortex-a53-machine-learning-vision-multimedia-and-industrial-iot:IMX8MPLUS)) and MIMX8ML6 (i.e., [iMX8M-Mini](https://www.nxp.com/products/processors-and-microcontrollers/arm-processors/i-mx-applications-processors/i-mx-8-applications-processors/i-mx-8m-mini-arm-cortex-a53-cortex-m4-audio-voice-video:i.MX8MMINI)).

Is it possible adding them?

**Comment by escherstair** [comment]
Hi @mcgordonite, I don't know.
I know there is the MCUXpresso SDK package from NXP, but I don't know who is in charge to publish a CMSIS pack.

**Comment by KeilChris** [comment]
NXP devices are supported via packs from NXP. The DFPs for i.MX8 are already a couple of years old and have never been updated. I doubt that they will work anyway in the tools. I suggest to reject this request.

**Comment by thegecko** [comment]
Thanks @KeilChris is there an avenue for @escherstair to request pack support from NXP for these targets?

**Comment by escherstair** [comment]
> Thanks @KeilChris is there an avenue for @escherstair to request pack support from NXP for these targets?

I don't think so.
This is the answer from NXP:

> NXP developed these DFP as part of agreement between NXP and ARM (KEIL) in past.
> That was business agreement and some DFPs were developed and provided to KEIL.
> However this was just business -
> so packages were delivered to KEIL and after that agreement expired.
> 
> All these DFPs were integrated to KEIL IDEs and were part of Kel software.
> 
> So summary - we here (NXP Tech support) - DO NOT- provide any DFPs to customers.
> 
> In other words You should apply to NXP management (or Keil management)
> to intiate new deal (agreement) for developing DFPs for KEIL.

From NXP point of view, DFP are a need/requirement of Keil users (and not a need of "generic" iMX8M users).
I'm not totally convinced about this, but this is NXP position, and I don't have way to change NXP mind.

**Comment by thegecko** [comment]
A colleague has pointed out to me that these devices are Cortex-A. The VS Code extensions we are building are currently targeting Cortex-M class devices only.

**Comment by escherstair** [comment]
Hi @thegecko

> A colleague has pointed out to me that these devices are Cortex-A. The VS Code extensions we are building are currently targeting Cortex-M class devices only.

this is not 100% correct.
They're HMP (Hetherogeneous Multicore Processors) and they have both Cortex-A cores (out of scoper for this extension) and Cortex-M cores.
The idea is using the extension for the Cortex-M cores.

**Comment by KeilChris** [comment]
Yes, that's correct. IT's HMP. Still, we require a pack for the M part which was supplied by NXP. If they do not want to do that anymore, we're out of luck here. Let me try my channels, but I have little hope.

**Comment by escherstair** [comment]
> I don't believe so, CMSIS Packs support GCC too
If someone has an open channel to NXP, he can try to convince them that DFP is used by GCC too, and it's not a "Keil tool" only.
Maybe they can reconsider their position (but I think is difficult)

**Comment by KeilChris** [comment]
Well I suppose that the i.MX SDK team is convinced that you need a pack only for MDK (which is not 100% true as IAR can work with it as well), so they are reluctant to create it. I'm still waiting for feedback.

**Comment by escherstair** [comment]
In case someone else is interested, I see tha NXP developed its own extension for VS Code
[NXP MCUXpresso for VS Code extension](https://github.com/nxp-mcuxpresso/vscode-for-mcux)
Basically it works, even if it's quite new and it needs some improvement.

**Comment by jkrech** [comment]
There is no further activity. NXP owns their CMSIS Packs and the decision about supported devices.
