### ISSUE TITLE
Sort "Active solution" by alphabetical order

### ISSUE THREAD

**Issue by VVESTM** [ARM-software/vscode-cmsis-csolution#32]
Hello, 

When using "Keil Studio Pack" and "Arm CMSIS csolution" extensions, it can be quite difficult to find the relevant "Active solution" in CMSIS context menu. Effectively, if we have several csolution.yml and cproject.yml files, the list is not sorted. And from one launch to the other, the order may vary.
 
Is it possible to have an alphabetical sort ?
![image](https://github.com/ARM-software/vscode-cmsis-csolution/assets/22098252/f7bc2bca-d95e-4d05-a9a0-665bdef1dcbf)

Thanks in advance for your help.

**Comment by VVESTM** [comment]
I am working on Windows.

With VSCode, I open a directory which contains several sub directories. In each subdirectories, I have a cproject.yml/csolution.yml:
![image](https://github.com/ARM-software/vscode-cmsis-csolution/assets/22098252/8eabc46b-57dc-42b6-95b0-7c0db53d801a)
(one cproject.yml per project and per board)

In VSCode, the view is like this:
![image](https://github.com/ARM-software/vscode-cmsis-csolution/assets/22098252/f34fd2af-cb9f-4153-9982-c0b4fafd62c7)

In "Active Solution", the different lines are not sorted. (This is not visible on my screen capture as I only took a subset of my projects)

**Comment by micque01** [comment]
Hi @VVESTM, thanks for the additional info. Version 0.25.0 of the csolution extension has just been released, which includes sorting of solutions and projects in the context drop-downs. Hopefully this fixes your issue!

**Comment by VVESTM** [comment]
Thanks a lot !!
