### ISSUE TITLE
Extension .cpp is not supported in uv2csolution

### ISSUE THREAD

**Issue by Jonny-vb** [ARM-software/vscode-cmsis-csolution#36]
Type: Bug Report

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.80.1
- Extension Version: 1.2.3
- Target Device: STM32F4
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

On trying to convert a uVision project to Csolution for evaluation, I get the error on every cpp file:
```
<Target> "TestTarget" <Group> OS <File> .\Source\main.cpp Extension .cpp is not supported
``` 

From what I can see, C++ us supported by csolution, so I'm not sure why the tool claims the cpp extension isn't supported?

**Comment by mcgordonite** [comment]
The latest release of the Csolution extension, 1.6.0, adds support for converting µVision projects with C++ files.
