### ISSUE TITLE
command:cmsis-csolution.getBinaryFile does not return the path to binary

### ISSUE THREAD

**Issue by AkiMakkonen-AlifSemi** [ARM-software/vscode-cmsis-csolution#42]
getBinaryFile returns the path to <project>.elf correctly with version v1.11.0.

Seems to return path to project folder root with version v1.11.1

**Comment by mcgordonite** [comment]
Hi @AkiMakkonen-AlifSemi, thanks for reporting this issue. It should be fixed in v1.11.2. Can you confirm that it is resolved for you?

**Comment by AkiMakkonen-AlifSemi** [comment]
Hi @mcgordonite, thank you for such a fast response. It works now!
