### ISSUE TITLE
command for getting project name

### ISSUE THREAD

**Issue by AkiMakkonen-AlifSemi** [ARM-software/vscode-cmsis-csolution#47]
Type: Feature Request

We can already get the "target type" and "build type" selected in the CONTEXT GUI, but sometimes it would be handy to get also the selected project's name when creating user defined tasks.

**Comment by jkrech** [comment]
This issue has not been addressed in quite some time. Is this still relevant for you?

**Comment by AkiMakkonen-AlifSemi** [comment]
This is not needed anymore.
