### ISSUE TITLE
Installing required packs for solution

### ISSUE THREAD

**Issue by atoyx** [ARM-software/vscode-cmsis-csolution#59]
Type: Feature Request

## description
- OS and Version: Win 10
- VS Code Version: 1.87.2
- Csolution Extension Version: 1.33.2

![image](https://github.com/ARM-software/vscode-cmsis-csolution/assets/43333560/f83e1fb1-3366-4233-ac6c-e54cb04b90fd)
i need another way to download this package ,because the time we cost is not visiable 

## Expected Behavior
load local package

**Comment by jkrech** [comment]
I am not sure I do understand your reason for needing another way to download the pack Keil::STM32H7xx_DFP@3.1.1 however you can run the pack installer of the CMSIS-Toolbox named `cpackget` from a terminal window in VSCode.
```
  cpackget add Keil::STM32H7xx_DFP@3.1.1
```
You can also locate the require pack version on the web in a browser:
https://www.keil.arm.com/packs/stm32h7xx_dfp-keil/versions/
The "Get Pack" drop down provides you the option to download it on your computer
Afterwards you can point to that file using cpackget:

```
  cpackget add Keil.STM32H7xx_DFP.3.1.1.pack
```

If you already have a pack file download you can use the above command as well.
Please let us  know whether this answers your question.

**Comment by atoyx** [comment]
![image](https://github.com/ARM-software/vscode-cmsis-csolution/assets/43333560/e97b45cc-88f3-4387-b255-5f17d8305343)
thanks a lot , i use cpackget load my package. But there still have a problem casuse i have set `cmsis-csolution.packCachePath` as `D:\\Users\\xx\\pack`, extension can't find the installed package. where are the platform-specific default path

**Comment by atoyx** [comment]
platform-specific default path is `C:\Users\<your name>\AppData\Local\arm\packs`

**Comment by atoyx** [comment]
i found the answer
![image](https://github.com/ARM-software/vscode-cmsis-csolution/assets/43333560/82f05030-98f4-4a75-a82f-b91a4439d0e2)
