### ISSUE TITLE
Configuration Wizard Replacement

### ISSUE THREAD

**Issue by FerdinandEn** [ARM-software/vscode-cmsis-csolution#64]
Type: Feature Request

OS and Version: Windows 11
VS Code Version: 1.88
CMSIS Solution 1.34.3

For *.h files, I can set the content graphically as in uVision. This does not work for other file types e.g. *.s , *.dbgconf

**Comment by ReinhardKeil** [comment]
Config Wizard is available, just opens a bit different.
See here https://developer.arm.com/documentation/108029/0000/Arm-CMSIS-csolution-extension/Use-the-Configuration-Wizard

**Comment by thorstendb-ARM** [comment]
Hi @FerdinandEn, thanks for pointing this out. We are currently working on enabling also other files.
