### ISSUE TITLE
Invisible buttons till hover are a genuine annoyance 

### ISSUE THREAD

**Issue by lmdanny** [ARM-software/vscode-cmsis-csolution#7]
Type: Feature Request

Wouldn't it be a good idea to either have the buttons for creating projects or changing components to be always visible, and if this cannot be done just move all the controls down and just add in a simple toolbar above all the other items.

Now I do know where to find them, but it wasn't easy :)

<img width="324" alt="image" src="https://user-images.githubusercontent.com/119610036/205219875-a8f5c7ee-9885-4c01-9701-3d2e28b205d9.png">

**Comment by lmdanny** [comment]
Okay, just reading through there seems this is already open since 2020

https://github.com/microsoft/vscode/issues/109030

That gives me little hope that this will be fixed or changed soon.

For users, I believe these particular features such as the component selection and perhaps also other functionality that is built in MDK currently and might come to the vscode extensions (I don't know the roadmap), a separate section with would not be a harm to the user's experience.

**Comment by mcgordonite** [comment]
Agreed, unless our team can contribute a fix up to VS Code I don't expect to see it fixed soon.

We'll investigate different options to improve the UX here.

**Comment by kanthanp** [comment]
This usability has now been fixed.

**Comment by mcgordonite** [comment]
Closing: the fix in https://github.com/microsoft/vscode/issues/109030 is now live in VS Code.
