### ISSUE TITLE
Cannot remove or delete a file included in the CMSIS tab

### ISSUE THREAD

**Issue by DBizz22** [ARM-software/vscode-cmsis-csolution#71]
Type: Bug Report

**Describe the bug**
- OS: Microsoft Windows 11 pro 
- Version: 10.0.22635 Build 22635
- VS Code Version: 1.90.1
- Extension Version: Arm CMSIS solution v1.36.0
- Target Device: PC
- Other extensions you installed (and if the issue persists after disabling them):
-(Description) Can add a new file or existing file to the different source group folders in the CMSIS tab but no option to remove files from the group. If the file is removed or deleted using the file explorer, it persists in the tab.

**To Reproduce**

**Expected behavior**

-Need an option to remove and rename files from source groups using CMSIS tab options and to refresh the files in the directory. 

**Code sample and logs**
- Code sample
- `tasks.json`
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "arm-debugger.flash",
            "serialNumber": "${command:device-manager.getSerialNumber}",
            "program": "${command:arm-debugger.getApplicationFile}",
            "cmsisPack": "${command:device-manager.getDevicePack}",
            "deviceName": "${command:cmsis-csolution.getDeviceName}",
            "processorName": "${command:cmsis-csolution.getProcessorName}",
            "problemMatcher": [],
            "label": "Flash Device"
        },
        {
            "type": "cmsis-csolution.build",
            "solution": "${command:cmsis-csolution.getSolutionPath}",
            "rebuild": false,
            "problemMatcher": [],
            "label": "cmsis-csolution.build: Build"
        }
    ]
}

**Screenshots**

<img width="1265" alt="image" src="https://github.com/ARM-software/vscode-cmsis-csolution/assets/149373399/e976c095-e1bd-4aaa-a3c9-d011b42b652c">

**Additional context**

Because of a mistake, I deleted one "fifa.h" file but it remains in the tab.

**Comment by jkrech** [comment]
Currently you can only remove a file from your project by editing the corresponding `*.cproject.yml` file.
In the CMSIS project outline view you can hover over your project/context  line and on the right end of the line three icons appear.
The middle one opens the `*.cproject.yml` file in the editor where you can simply remove the line

```yaml
    - group: Source Group 1
      files:
        ...
        - file: fifa.h
        ...
```

Please excuse the inconvenience. This is something we plan to the product at a later point.
