### ISSUE TITLE
The reference of the compile_commands.json file in `.clangd` is incorrect if the outdir is refined

### ISSUE THREAD

**Issue by jkrech** [ARM-software/vscode-cmsis-csolution#74]
<!-- 
 if you specify another out directory, the .clangd file is still generated with the default folder

specified in csolution.yml:
```
  output-dirs: outdir: ./proj/out
```
`.clangd` file:
```
CompileFlags: CompilationDatabase: c:\....projectdir\out\........
```

Another issue:
if the csolution/cproject is not in root directory .clangd is built in the project files folder, but the file needs to be in the root dir, to my knowledge there is no way around to put the files to the root directory.

**Comment by ReinhardKeil** [comment]
We just released the CMSIS Solution extension 1.40 that fixes this problem.

https://marketplace.visualstudio.com/items?itemName=Arm.cmsis-csolution
