### ISSUE TITLE
Pack index not updated

### ISSUE THREAD

**Issue by KimmoVaisanen-AlifSemi** [ARM-software/vscode-cmsis-csolution#76]
Type: Bug Report

**Describe the bug**
- OS and Version: Ubuntu 22.04 or Windows 11
- VS Code Version: 1.94.0
- Extension Version: 1.38.0

We had a new pack version uploaded into Keil CMSIS pack repository, but when user updates his/her solution with the new the pack version and system will try to install the new pack version, installation gave an error `E: pack version not found in the pdsc file`.

After debugging and googling the issue, I found that the pdsc file in .cache/arm/packs/.Web is not updated with the latest version therefore resulting in the error.

Manual installation e.g. with `cpackget add AlifSemiconductor::Ensemble@1.3.0` gave the same error. Giving a full url for `cpackget` works ok and then pack can be used.

This can be worked around by either deleting the pdsc file from .Web directory or running `cpackget update-index`, but should system do this automatically?

If yes, I don't know if this an issue with the vscode-cmsis-csolution extension or the cmsis-toolbox.

**Comment by jkrech** [comment]
The current position is that it is not efficient to always update the index.pidx with cpackget commands that access the index.pidx.
Instead the proposal is to implement this in the CMSIS Solution extension. The MDK uVision PackInstaller maintains the file ./Web/update.cfg containing the date of the last update. On initialization of the CMSIS Solution extension the file would be read. If the date is not the current date, then the cpackget update-index is executed and the current date writting to the update.cfg file.

**Comment by ReinhardKeil** [comment]
We are aware of the issue and work on towards user-friendly solution. For now use this as a workaround.

Open the Terminal window and enter the command:
```
cpackget update-index
```

**Comment by KimmoVaisanen-AlifSemi** [comment]
Ok. Thank you.

Do you happen to have any schedule for this yet?

**Comment by ReinhardKeil** [comment]
Yes, it will be part of CMSIS-Toolbox 2.7 planned for December 2024.

**Comment by KimmoVaisanen-AlifSemi** [comment]
Thank you again. 

Since you have a plan for this, this ticket can be closed. Unless you want to keep it for tracking purposes.

**Comment by ReinhardKeil** [comment]
This will be solved by https://github.com/Open-CMSIS-Pack/cpackget/issues/355 + https://github.com/Open-CMSIS-Pack/cpackget/issues/358
