### ISSUE TITLE
Use Web Services and Local Packs for Boards/Devices/Examples

### ISSUE THREAD

**Issue by ReinhardKeil** [ARM-software/vscode-cmsis-csolution#79]
In v1.40 new device or board support must be installed manually using `cpackget`.

For examples, apparently a web service is used to download it. Also examples from local packs are shown.
Recommendation: Add the web service feature also to boards and devices and automate the download of packs (as it was in the previous version of the extension).

**Comment by JonatanAntoni** [comment]
https://jira.arm.com/browse/MCUTO-292
https://jira.arm.com/browse/MCUTO-309

**Comment by jkrech** [comment]
CMSIS Solution 1.42 uses web services to retrieve boards, devices in addition to examples on top of boards, devices and examples from installed packs.
