### ISSUE TITLE
UX simplification: Manage Solution

### ISSUE THREAD

**Issue by ReinhardKeil** [ARM-software/vscode-cmsis-csolution#81]
Suggest to slight improve the description and remove redundant text in "Manage Solution" as shown below.

![image](https://github.com/user-attachments/assets/6573c70e-b7d0-45fb-b23d-73cf49d063f6)

**Comment by ReinhardKeil** [comment]
@jkrech, yes this is even better

**Comment by jkrech** [comment]
Also consider changes requested in #93 while working on this.

**Comment by thorstendb-ARM** [comment]
Applyes changes:
![image](https://github.com/user-attachments/assets/ee866e36-0928-49bd-8722-92283dc1531b)

**Comment by jkrech** [comment]
confirmed in internal build from main branch 2024-12-05 - will be in release version 1.46
