### ISSUE TITLE
Enable `clangd` for all projects that belong to context-set

### ISSUE THREAD

**Issue by ReinhardKeil** [ARM-software/vscode-cmsis-csolution#85]
Currently only the first project of a context-set is part of the file `.vscode\settings.json`, for example:
{
    "clangd.arguments": [
        "--compile-commands-dir=c:\\w\\MDK-Middleware\\.ci\\out\\FileSystem\\CM4\\Debug"
    ]
}

This `clangd.arguments` list should contain all projects that are selected in the `cbuild-set.yml` file which reflects the current selected context-set.

**Comment by jkrech** [comment]
Available in CMSIS Solution 1.42
