### ISSUE TITLE
Consider renaming "View Container", "Output Window"

### ISSUE THREAD

**Issue by ReinhardKeil** [ARM-software/vscode-cmsis-csolution#86]
**View Container**

VS Code view containers allow to expose features from other extensions, for example to extend context menus. We should therefore settle on a meaningful name. 

Right now, "keil-studio" was chosen.  I suggest to rename the view container to "cmsis-solution".

![image](https://github.com/user-attachments/assets/48bed7cd-75d8-431e-815d-27a3d45f4e8e)

**Output Window**

The output window allows an extension to post messages.  The current name of this window is "CMSIS Build Manager".  I would recommend to change the name to "CMSIS Solution" as it connects it better to the extension itself.  I also believe it shows not just build messages (as the example below contains the setup command executed by cbuild).

![image](https://github.com/user-attachments/assets/7ecfc426-2204-42d3-afa4-51095d9823da)

**Comment by jkrech** [comment]
View Container got renamed for next release (1.45)
Output channel was renamed to CMSIS Solution in last release (1.44)
