### ISSUE TITLE
Access to component documentation, improve 

### ISSUE THREAD

**Issue by ReinhardKeil** [ARM-software/vscode-cmsis-csolution#87]
Current, the component documentation is exposed as file in the outline view.

Change this to an [button with link Icon](https://github.com/microsoft/vscode-codicons/blob/main/src/icons/link-external.svg) that is available on the component itself (similar to Run Generator).

![image](https://github.com/user-attachments/assets/f6f1e2b8-da2d-41a7-bce5-ecf728e5bbb2)

Other discussion points:
 - is it possible to make buttons permanent instead of hover-over and is this a better approach?  For example "Layer" have the "Open clayer.yml file" button permanent, should it be hover-over instead?
 - The dark blue color of the link icon is hard to see on dark themes; suggest to use white color instead. Dark blue works fine on light color themes.

**Comment by edriouk** [comment]
This PR made the documentation accessible via button: https://github.com/Arm-Debug/vscode-cmsis-csolution/pull/1882
Doc file are no longer shown as child items of the component.
Open pojnts: 
- Icon can be changed. 
- open doc in KSC
- permanent buttons (if possible)

**Comment by jkrech** [comment]
a) For the links to documentation the [books icon](https://github.com/microsoft/vscode-codicons/blob/main/src/icons/book.svg) is used 
b) This icon does not use the blue color and is well visible in light and dark mode
c) The icon is only displayed on hover over / selection of the component
d) "Open clayer.yml file" button is also displayed dynamically on hover-over or select

The discussion about whether icons should be permanently displayed is continued here: #150

**Comment by ReinhardKeil** [comment]
The only button that I think should be permanent is the "Run Generator" as the component is different from others.
