### ISSUE TITLE
Consider to add GCC memory usage to `cdefault.yml`

### ISSUE THREAD

**Issue by ReinhardKeil** [ARM-software/vscode-cmsis-csolution#89]
The attached `cdefault.yml` enables some neat GCC features. 
[cdefault.yaml.txt](https://github.com/user-attachments/files/17378019/cdefault.yaml.txt)

**Comment by jkrech** [comment]
I have raised this enhancement in Open-CMSIS-Pack/devtools #1845 - should we close it here?
