### ISSUE TITLE
Consider to use "<unnamed>" instead of "Default"

### ISSUE THREAD

**Issue by ReinhardKeil** [ARM-software/vscode-cmsis-csolution#9]
In the CMSIS Context Window it seems the term "Default" is used when no build-type or target-type is specified in the csolution file.

As "Default" is a valid build-type or target-type name, this might get confusing.  Instead I suggest to use the string "\<unnamed\>"

See this picture
![image](https://user-images.githubusercontent.com/8268058/205961776-a7761a58-4092-40df-8827-93aa84c2ae20.png)

**Comment by ReinhardKeil** [comment]
Both `\<undefined\>` or `\<unnamed\>` would work for me.  It should just be clear that this is not a standard `build-type` name.

**Comment by mcgordonite** [comment]
This was resolved in version 0.11.0.
