### ISSUE TITLE
Templates show no description line

### ISSUE THREAD

**Issue by ReinhardKeil** [ARM-software/vscode-cmsis-csolution#94]
**Describe the bug**

Examples, Templates, and Layers have a brief description.  However for Templates the description is not shown.

![image](https://github.com/user-attachments/assets/52df16d5-f3eb-41eb-bc20-58d035ad5f9e)

**Expected behavior**

Show the description that is in the PDSC file:
https://github.com/ReinhardKeil/STM32U5xx_DFP/blob/main/Keil.STM32U5xx_DFP.pdsc#L1923

**Comment by RobertRostohar** [comment]
Would be also good to display the origin of the templates and also origin of the reference applications and examples. Maybe displayed when hovering over. If it comes from a certain pack, the pack version could be shown, or if it comes from the web.

**Comment by thorstendb-ARM** [comment]
Description is shown in the DataManager "generalized" Version of the Tree Dropdowns:
![image](https://github.com/user-attachments/assets/020322ec-c0fb-4bf4-aa7b-902e013cdd51)

What description should we put on the hard-coded, internal ones?

**Comment by ReinhardKeil** [comment]
@thorstendb-ARM  

Brief description for internal Templates:

Blank: Start from scratch with a `main.c` and CMSIS device startup
TrustZone: Start from scratch with secure/non-secure project

**Comment by thorstendb-ARM** [comment]
Done:
![image](https://github.com/user-attachments/assets/e23eaf96-c1b8-4570-9469-c97c7797df2f)

**Comment by jkrech** [comment]
Confirmed with internal build from main branch: 2024-12-05
