### ISSUE TITLE
Solution projects of local installed packs are not available with Create New Solution

### ISSUE THREAD

**Issue by ReinhardKeil** [ARM-software/vscode-cmsis-csolution#95]
To duplicate:
  - Install: https://github.com/VladimirUmek/NXP_FRDM-MCXN947_BSP/releases/tag/v19.1.0-dev
  - Use from CMSIS View - Create New solution.

It does not show this "Blinky" example:
https://github.com/VladimirUmek/NXP_FRDM-MCXN947_BSP/blob/main/NXP.FRDM-MCXN947_BSP.pdsc#L1708

![image](https://github.com/user-attachments/assets/9a69f91e-982d-4c7e-8e75-b3f265624189)

**Environment**
- OS and Version: Windows
- Extension Version: CMSIS-Solution 1.40

**Comment by jkrech** [comment]
This works with CMSIS Solution extension 1.44
