### ISSUE TITLE
Display all board revisions provided by different packs

### ISSUE THREAD

**Issue by TeoMahnic** [ARM-software/vscode-cmsis-csolution#97]
Display all available board revisions if installed packs provide different board revisions. Only one is currently shown in the `Create new solution - Target Board` menu. 

### Example of current behavior
Install the following packs:
```sh
cpackget add Keil::STM32F7xx_DFP@2.16.0
cpackget add Keil::STM32F7xx_DFP@3.0.0
cpackget add Keil::STM32F769I-EVAL_BSP@1.0.0
```
Use `Create new solution` button in VS Code. In the `Target Board` dropdown only STM32F769I-EVAL (Rev.A) is listed. The behavior is not reproducible every time, sometimes only STM32F769I-EVAL (Rev.B) is listed.

![image](https://github.com/user-attachments/assets/54f3b476-6660-4f38-8d06-9f46c9a7dd06)

- STM32F769I-EVAL (Rev.A) is described in Keil::STM32F7xx_DFP@2.16.0
- STM32F769I-EVAL (Rev.B) is described in Keil::STM32F769I-EVAL_BSP@1.0.0

#### Environment
- Windows 11
- Arm CMSIS Solution 1.40.0
- CMSIS-Toolbox 2.6.1 with empty CMSIS_PACK_ROOT

#### Possible workaround
Remove pack which provides the unwanted board revision.

**Comment by jkrech** [comment]
My expectation is that we would only read the latest version of a pack for listing boards and devices when we start a new project.
Since the board is not present in the latest pack version Keil::STM32F7xx_DFP@3.0.0 I would expect to always see Rev. B.

After installing a pack using cpackget, have you restarted VSCode?

**Comment by TeoMahnic** [comment]
VS Code was not running during installation of the mentioned packs and was only reopened after all packs were successfully installed.

**Comment by thorstendb-ARM** [comment]
Seems to toggle on CTRL-R (reload VSCode), and stable when closing and opening "Create new".

**Comment by ReinhardKeil** [comment]
> My expectation is that we would only read the latest version of a pack for listing boards and devices when we start a new project. Since the board is not present in the latest pack version Keil::STM32F7xx_DFP@3.0.0 I would expect to always see Rev. B.
> 
> After installing a pack using cpackget, have you restarted VSCode?

I would argue that it should show both board revisions.  Customers may still have Rev A. and there might be a hardware difference.

**Comment by thorstendb-ARM** [comment]
Duplicates on name get filtered out in UI for some reason. After disabling the filtering:
![image](https://github.com/user-attachments/assets/6efed0c6-205b-45c5-8fdc-248a2410a4e1)

**Comment by thorstendb-ARM** [comment]
New version for testing: https://github.com/Arm-Debug/vscode-cmsis-csolution/actions/runs/11501199177
- removed filter for duplicate boards
- removed Arm AVH and Debugger from vcpkg requirements

**Comment by jkrech** [comment]
> I would argue that it should show both board revisions. Customers may still have Rev A. and there might be a hardware difference.

We are removing the filtering of boards with different Brevision which is expected to show both boards
- STM32F769I-EVAL (Rev.A)
- STM32F769I-EVAL (Rev.B)

In my view a mistake was made by the Pack Vendor:
STM32F769I-EVAL (Rev.A) is described in Keil::STM32F7xx_DFP@2.16.0
but no longer in the next pack revision: Keil::STM32F7xx_DFP@3.0.0
nor in the newly introduced dedicated BSP, instead only 
STM32F769I-EVAL (Rev.B) is described in Keil::STM32F769I-EVAL_BSP@1.0.0

I am not sure if we should expect that the discovery of boards and devices must read through all pack versions or we just read the latest pack version.

Note that only Rev B is listed on keil.arm.com:
https://www.keil.arm.com/boards/?q=STM32F769I-EVAL

**Comment by ReinhardKeil** [comment]
Yes, I agree.  If a later version of the pack only contains Rev. B we should only show Rev. B.

We should review how packs are loaded by the system.  It should only load latest.

**Comment by jkrech** [comment]
CMSIS-Solution v 1.42 now shows both pack versions but only reads the latest installed pack version.
